name: Update WordPress.org assets

on:
  push:
    branches:
      - main
    paths:
      - ".wordpress-org/**"
  workflow_dispatch:

jobs:
  assets:
    name: Push assets to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: WordPress.org asset update
        uses: 10up/action-wordpress-plugin-asset-update@2480306f6f693672726d08b5917ea114cb2825f7 # v2.2.0
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ai-provider-for-voyage-ai
          IGNORE_OTHER_FILES: true
